name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ERSO: ${{ github.workspace }}/erso
    steps:
      - uses: actions/checkout@v4

      - name: Checkout pturso
        uses: actions/checkout@v4
        with:
          repository: Resonious/pturso
          path: pturso-repo

      - name: Symlink pturso
        run: ln -s ${{ github.workspace }}/pturso-repo ../pturso

      - name: Download erso binary
        run: |
          curl -L -o erso https://github.com/Resonious/pturso/releases/download/0.0.1/erso-x86_64-linux
          chmod +x erso

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.14.0"
          rebar3-version: "3"

      - name: Download Gleam dependencies
        run: gleam deps download

      - name: Run Gleam tests
        run: gleam test
